### ISSUE TITLE
Request for assistance to get `esbuild-plugin-istanbul` working

### ISSUE THREAD

**Issue by edumserrano** [abraha2d/esbuild-plugin-istanbul#1]
Hi @abraha2d,

## Description

I've been trying to use your package in an Angular 17 app which uses vite+esbuild but haven't been successful yet.

You can view the sample app app [/demos/code-coverage-with-istanbul-via-esbuild-plugin](https://github.com/edumserrano/playwright-adventures/tree/code-coverage-esbuild/demos/code-coverage-with-istanbul-via-esbuild-plugin). It's part of the [code-coverage-esbuild](https://github.com/edumserrano/playwright-adventures/tree/code-coverage-esbuild) branch.

## What I've done so far

1) Created an Angular 17 app
2) Used the [@angular-builders/custom-esbuild](https://www.npmjs.com/package/@angular-builders/custom-esbuild) to allow me to customize Angular's ESBuild configuration. This allowed me to [specify files to be executed as ESBuild plugins](https://github.com/edumserrano/playwright-adventures/blob/a12b348ac7b9a48f6c7a8fa8c1c72f324443f5b9/demos/code-coverage-with-istanbul-via-esbuild-plugin/angular.json#L16C1-L19C15)
3) Added a couple of ESBuild plugin files:

    - [code-coverage-3.ts](https://github.com/edumserrano/playwright-adventures/blob/code-coverage-esbuild/demos/code-coverage-with-istanbul-via-esbuild-plugin/code-coverage-3.ts): this file contains a simple plugin I coded to log to the console the ESBuild plugins that are configured for this app. I was using this just for debug purposes.
    - [code-coverage-4.ts](https://github.com/edumserrano/playwright-adventures/blob/code-coverage-esbuild/demos/code-coverage-with-istanbul-via-esbuild-plugin/code-coverage-4.ts): this file is using your `esbuild-plugin-istanbul` package to instrument `.ts` files with Istanbul.

## How to run

1) Clone the [code-coverage-esbuild](https://github.com/edumserrano/playwright-adventures/tree/code-coverage-esbuild) branch.
2) Go to  [/demos/code-coverage-with-istanbul-via-esbuild-plugin](https://github.com/edumserrano/playwright-adventures/tree/code-coverage-esbuild/demos/code-coverage-with-istanbul-via-esbuild-plugin)
3) Run `npm i` to install the npm packages.
4) Run `npm start` to run the app.

## How I checked that code coverage isn't being collected

1) After starting the app,  go to [http://localhost:4200/](http://localhost:4200/)
2) Check for code coverage instrumentaton by going to the dev tools and on the console executing: `window.__coverage__`.
3) Note how `window.__coverage__` is `undefined`.

> [!NOTE]
>
> If you follow the steps for the `How to run` and `How I checked that code coverage isn't being collected` for the app at [/demos/code-coverage-with-istanbul-via-webpack-babel-plugin](https://github.com/edumserrano/playwright-adventures/tree/code-coverage-esbuild/demos/code-coverage-with-istanbul-via-webpack-babel-plugin) then  `window.__coverage__` won't be undefined.
>
> The app at `/demos/code-coverage-with-istanbul-via-webpack-babel-plugin` is also an Angular 17 app but is using webpack instead of esbuild and for the instrumentation it uses the [babel-plugin-istanbul](https://www.npmjs.com/package/babel-plugin-istanbul) npm package.

## Help

**Could you provide any guidance on how to use your package to instrument the sample Angular 17 app I linked ?**

**Comment by edumserrano** [comment]
I've recorded some videos to better show the issue I'm facing.

## Using esbuild-plugin-istanbul I get no coverage data

This video shows that `window.__coverage__` is not populated when using `esbuild-plugin-istanbul`. The app used in this video is the one at [/demos/code-coverage-with-istanbul-via-esbuild-plugin](https://github.com/edumserrano/playwright-adventures/tree/code-coverage-esbuild/demos/code-coverage-with-istanbul-via-esbuild-plugin).

https://github.com/abraha2d/esbuild-plugin-istanbul/assets/15857357/482af401-6638-43fb-ad8b-35aa9edd6598

## Using babel-plugin-istanbul I do get coverage data

This video shows that `window.__coverage__` is populated when using `babel-plugin-istanbul`.  The app used in this video is the one at [/demos/code-coverage-with-istanbul-via-webpack-babel-plugin](https://github.com/edumserrano/playwright-adventures/tree/code-coverage-esbuild/demos/code-coverage-with-istanbul-via-webpack-babel-plugin).

https://github.com/abraha2d/esbuild-plugin-istanbul/assets/15857357/1cb11635-9d03-48f7-ab78-975971a7e395

**Comment by abraha2d** [comment]
Hi @edumserrano, that's weird... I will take a look at this as soon as I can.

**Comment by abraha2d** [comment]
Ok, I'll prefix this by saying I'm not very familiar with Angular at all, but it looks like this demo is using ESBuild via Vite, not directly?

Based on https://github.com/vitejs/vite/issues/2238#issuecomment-808943494, only a subset of ESbuild plugin functionality can be used with Vite since it only uses the ESbuild for transpiling (via the transform API). `esbuild-plugin-istanbul` relies on the "on-load" functionality, which is explicitly called out there as not being supported by the ESbuild transform API.

You might be able to use something like https://github.com/iFaxity/vite-plugin-istanbul instead.

**Comment by edumserrano** [comment]
Thank you for the pointers. I'm also not familiar enough with Angular/Vite/ESBuild to figure out how to get this stuff to work. 

What I've come to know is that Angular does not expose its ESBuild configuration so I had to use [@angular-builders/custom-esbuild](https://www.npmjs.com/package/@angular-builders/custom-esbuild) to allow me to customize Angular's ESBuild configuration and add some plugin.

It seems though that what you found means that I can't follow this approach. But I'm still stuck because I haven't found anyway of extending Angular's Vite configuration, which is also not exposed. That means I can't use your suggestion of trying [https://github.com/iFaxity/vite-plugin-istanbul](https://github.com/iFaxity/vite-plugin-istanbul) because I don't know how to extend Angular's `vite.config.js`.

Thank you @abraha2d , I'm closing this since you have been able to root cause the problem and it's nothing to do with your plugin.

**Comment by SDAdham** [comment]
Hello team, anyone figured how to get code coverage with the new angular build esbuild? or `@angular-builders/custom-esbuild`?
